app/css/grinexplorer/explorer/urls.py
from django.urls import path

from .views import BlockList, BlocksByHeight, BlockDetail, Search


urlpatterns = [
    path("", BlockList.as_view(), name="block-list"),
    path("block/<int:height>", BlocksByHeight.as_view(), name="blocks-by-height"),
    path("block/<str:pk>", BlockDetail.as_view(), name="block-detail"),
    path("search", Search.as_view(), name="search"),
]

app/css/grinexplorer/grinexplorer/urls.py
from django.urls import include, path


urlpatterns = [
    path("", include("explorer.urls")),
]

app/css/grinexplorer/blockchain/models.py
from django.db import models


class Block(models.Model):
    hash = models.CharField(
        max_length=64,
        db_index=True,
        primary_key=True,
    )

    version = models.IntegerField()

    height = models.IntegerField(
        db_index=True,
    )

    previous = models.ForeignKey(
        related_name="children_set",
        to="Block",
        on_delete=models.PROTECT,
        db_index=True,
        null=True,
    )

    timestamp = models.DateTimeField()

    utxo_root = models.CharField(max_length=64)

    range_proof_root = models.CharField(max_length=64)

    kernel_root = models.CharField(max_length=64)

    nonce = models.TextField()

    difficulty = models.IntegerField()

    total_difficulty = models.IntegerField()

    @property
    def fees(self):
        return sum(self.kernel_set.all().values_list("fee", flat=True))


class Input(models.Model):
    block = models.ForeignKey(
        to=Block,
        on_delete=models.PROTECT,
        db_index=True,
    )

    data = models.CharField(max_length=66)


class Output(models.Model):
    OUTPUT_TYPE = (
        ("Transaction", "Transaction"),
        ("Coinbase", "Coinbase"),
    )

    block = models.ForeignKey(
        to=Block,
        on_delete=models.PROTECT,
        db_index=True,
    )

    output_type = models.TextField(
        choices=OUTPUT_TYPE
    )

    commit = models.CharField(max_length=66)

    switch_commit_hash = models.CharField(max_length=40)

    height = models.IntegerField()

    lock_height = models.IntegerField()

    spent = models.BooleanField()

    proof_hash = models.CharField(max_length=64)


class Kernel(models.Model):
    block = models.ForeignKey(
        to=Block,
        on_delete=models.PROTECT,
        db_index=True,
    )

    features = models.TextField()

    fee = models.IntegerField()

    lock_height = models.IntegerField()

    excess = models.CharField(max_length=66)

    excess_sig = models.CharField(max_length=142)

app/css/grinexplorer/explorer/models.py
from django.db import models

# Create your models here.

app/css/grinexplorer/blockchain/views.py
from django.shortcuts import render

# Create your views here.

app/css/grinexplorer/explorer/views.py
from django.db.models import Count, Max, Min
from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import redirect

from blockchain.models import Block, Output


class BlockList(ListView):
    template_name = "explorer/block_list.html"
    context_object_name = "block_list"

    queryset = Block.objects.order_by("-timestamp")
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["highest_block"] = Block.objects.order_by("height").last()
        context["latest_block"] = Block.objects.order_by("timestamp").last()
        context["total_emission"] = Output.objects.filter(output_type="Coinbase").count() * 50

        context["competing_chains"] = Block.objects \
                                           .filter(height__gte=context["highest_block"].height - 100) \
                                           .values("height") \
                                           .annotate(cnt=Count("height")) \
                                           .aggregate(Max("cnt"))["cnt__max"]
        context["forked_at"] = Block.objects \
                                    .filter(height__gte=context["highest_block"].height - 1000) \
                                    .values("height") \
                                    .annotate(cnt=Count("height")) \
                                    .filter(cnt__gt=1) \
                                    .aggregate(Min("height"))["height__min"]

        return context


class BlockDetail(DetailView):
    model = Block

    template_name = "explorer/block_detail.html"
    context_object_name = "blk"


class BlocksByHeight(TemplateView):
    template_name = "explorer/blocks_by_height.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["blocks"] = self.blocks
        context["height"] = self.height

        return context

    def get(self, request, height):
        self.blocks = Block.objects.filter(height=height).order_by("-total_difficulty")
        self.height = height

        if len(self.blocks) == 1:
            return redirect("block-detail", pk=self.blocks[0].hash, permanent=False)
        else:
            return super().get(request)


class Search(TemplateView):
    template_name = "explorer/search_results.html"
    results = None
    q_isdigit = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["q"] = self.q
        context["q_isdigit"] = self.q_isdigit
        context["results"] = self.results

        return context

    def get(self, request):
        self.q = request.GET.get("q", "").strip()

        # search query is valid block height
        if self.q.isdigit():
            self.q_isdigit = True

            if Block.objects.filter(height=self.q).count():
                return redirect("blocks-by-height", height=self.q, permanent=False)

        # require at least 8 characters
        if len(self.q) >= 6:
            self.results = Block.objects.filter(hash__startswith=self.q)

            # if only one result, redirect to found block
            if self.results.count() == 1:
                return redirect("block-detail", pk=self.results[0].hash, permanent=False)

        return super().get(request)

app/css/grinexplorer/explorer/templates/explorer/block_detail.html
{% extends "base.html" %}

{% load humanize %}

{% block content %}
  <h2>Block {{ blk.height }}</h2>
  <p>
	Hash: <code>{{ blk.hash }}</code>
  </p>

  <table class="table table-bordered table-hover">
	<tr>
	  <td>Height</td>
	  <td>{{ blk.height }}</td>
	</tr>
	<tr>
	  <td>Version</td>
	  <td>{{ blk.version }}</td>
	</tr>
	<tr>
	  <td>Previous Block</td>
	  <td>
		{% if blk.height == 0 %}
		  <em>(None, this is the Genesis Block)</em>
		{% else %}
		  <a href="/block/{{ blk.previous.hash }}" title="{{ blk.previous.hash }}">{{ blk.previous.hash | slice:":8" }}...</a>
		{% endif %}
	  </td>
	</tr>
	<tr>
	  <td>Age</td>
	  <td>{{ blk.timestamp | date:"Y-m-d, H:i:s" }} UTC</td>
	</tr>
	<tr>
	  <td>Block Difficulty</td>
	  <td>{{ blk.difficulty }}</td>
	</tr>
	<tr>
	  <td>Cumulative Difficulty</td>
	  <td>{{ blk.total_difficulty }}</td>
	</tr>
	<tr>
	  <td>Block Reward</td>
	  <td>50</td>
	</tr>
	<tr>
	  <td>Fees</td>
	  <td>{{ blk.fees }}</td>
	</tr>
	<tr>
	  <td># TX Kernels</td>
	  <td>{{ blk.kernel_set.all.count }}</td>
	</tr>
	<tr>
	  <td># Inputs</td>
	  <td>{{ blk.input_set.all.count }}</td>
	</tr>
	<tr>
	  <td># Outputs</td>
	  <td>{{ blk.output_set.all.count }}</td>
	</tr>
  </table>

  <details>
	<summary>Inputs ({{ blk.input_set.all.count }})</summary>

	<table class="table table-bordered table-hover">
	  <thead class="thead-light">
		<tr>
		  <th>Data</th>
		</tr>
	  </thead>
	  <tbody>
		{% for input in blk.input_set.all %}
		  <tr>
			<td style="font-family:monospace;">{{ input.data }}</td>
		  </tr>
		{% endfor %}
	  </tbody>
	</table>
  </details>

  <br>

  <details>
	<summary>Outputs ({{ blk.output_set.all.count }})</summary>

	<table class="table table-bordered table-hover">
	  <thead class="thead-light">
		<tr>
		  <th>Output Type</th>
		  <th>Spent</th>
		</tr>
	  </thead>
	  <tbody>
		{% for output in blk.output_set.all %}
		  <tr>
			<td>{{ output.output_type }}</td>
			<td>{{ output.spent }}</td>
		  </tr>
		{% endfor %}
	  </tbody>
	</table>
  </details>

  <br>

  <details>
	<summary>Kernels ({{ blk.kernel_set.all.count }})</summary>

	<table class="table table-bordered table-hover">
	  <thead class="thead-light">
		<tr>
		  <th>Features</th>
		  <th>Fee</th>
		</tr>
	  </thead>
	  <tbody>
		{% for kernel in blk.kernel_set.all %}
		  <tr>
			<td>{{ kernel.features }}</td>
			<td>{{ kernel.fee }}</td>
		  </tr>
		{% endfor %}
	  </tbody>
	</table>
  </details>

{% endblock content %}

app/css/grinexplorer/explorer/templates/explorer/block_list.html
{% extends "base.html" %}

{% load humanize %}

{% block content %}
  <br>

  <div class="row">
	<div class="col-sm-6 col-md-3">
	  <div class="card">
		<div class="card-header">
		  Chain Height
		</div>
		<div class="card-body">
		  <h4 class="card-title">{{ highest_block.height | intcomma }}</h4>
		</div>
	  </div>
	</div>

	<div class="col-sm-6 col-md-3">
	  <div class="card">
		<div class="card-header">
		  Latest Block
		</div>
		<div class="card-body">
		  <h4 class="card-title">{{ latest_block.timestamp | naturaltime }}</h4>
		</div>
	  </div>
	</div>

	<div class="col-sm-6 col-md-3">
	  <div class="card">
		<div class="card-header">
		  Difficulty
		</div>
		<div class="card-body">
		  <h4 class="card-title">{{ latest_block.difficulty | intcomma }}</h4>
		</div>
	  </div>
	</div>

	<div class="col-sm-6 col-md-3">
	  <div class="card">
		<div class="card-header">
		  Emission
		</div>
		<div class="card-body">
		  <h4 class="card-title">{{ total_emission | intcomma }}</h4>
		</div>
	  </div>
	</div>
  </div>

  <br>

  {% if competing_chains > 1 %}
	<div class="alert alert-danger" role="alert">
	  <strong>Fork detected!</strong>
	  We've detected {{ competing_chains | apnumber }} competing chains, forked at <a href="/block/{{ forked_at }}">Block {{ forked_at }}</a>. Stay wary!
	</div>
  {% endif %}

  {% if block_list %}
	<h2>Latest Blocks</h2>

	<table class="table table-bordered table-hover">
	  <thead class="thead-light">
		<tr>
		  <th>Height</th>
		  <th>Hash</th>
		  <th>Age</th>
		  <th># kernel</th>
		  <th># in</th>
		  <th># out</th>
		</tr>
	  </thead>
	  <tbody>
		{% for blk in block_list %}
		  <tr>
			<td><a href="/block/{{ blk.height }}">{{ blk.height }}</a></td>
			<td><a href="/block/{{ blk.hash }}">{{ blk.hash }}</a></td>
			<td>{{ blk.timestamp | naturaltime}}</td>
			<td>{{ blk.kernel_set.all.count }}</td>
			<td>{{ blk.input_set.all.count }}</td>
			<td>{{ blk.output_set.all.count }}</td>
		  </tr>
		{% endfor %}
	  </tbody>
	</table>

	{% if is_paginated %}
	  <ul class="pagination justify-content-center">
		{% if page_obj.has_previous %}
		  <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo; newer blocks</a></li>
		{% else %}
		  <li class="page-item disabled"><a class="page-link" href="#">&laquo; newer blocks</a></li>
		{% endif %}
		<li class="page-item disabled">
		  <a class="page-link" href="#">page {{ page_obj.number }} / {{ paginator.num_pages }}</a>
		</li>
		{% if page_obj.has_next %}
		  <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">older blocks &raquo;</a></li>
		{% else %}
		  <li class="page-item disabled"><a class="page-link" href="#">older blocks &raquo;</a></li>
		{% endif %}
	  </ul>
	{% endif %}

  {% else %}
	Sorry, there was an error fetching the list of blocks. Please try again later.
  {% endif %}
{% endblock content %}

app/css/grinexplorer/explorer/templates/explorer/blocks_by_height.html
{% extends "base.html" %}

{% load humanize %}

{% block content %}
  <h2>Block {{ height }}</h2>

  <p>
	There was a fork in the blockchain resulting in several competing blocks at this height:
  </p>

  <table class="table table-bordered table-hover">
	<thead class="thead-light">
	  <tr>
		<th>Hash</th>
		<th>Age</th>
		<th>Cumulative Difficulty</th>
		<th># kernel</th>
		<th># in</th>
		<th># out</th>
	  </tr>
	</thead>
	<tbody>
	  {% for blk in blocks %}
		<tr>
		  <td><a href="/block/{{ blk.hash }}">{{ blk.hash }}</a></td>
		  <td>{{ blk.timestamp | naturaltime}}</td>
		  <td>{{ blk.total_difficulty | intcomma }}</td>
		  <td>{{ blk.kernel_set.all.count }}</td>
		  <td>{{ blk.input_set.all.count }}</td>
		  <td>{{ blk.output_set.all.count }}</td>
		</tr>
	  {% endfor %}
	</tbody>
  </table>

{% endblock content %}

app/css/grinexplorer/explorer/templates/explorer/search_results.html
{% extends "base.html" %}

{% load humanize %}

{% block content %}
  <h2>Search Results for "{{ q }}"</h2>

  {% if results %}
	<table class="table table-bordered table-hover">
	  <thead class="thead-light">
		<tr>
		  <th>Hash</th>
		  <th>Age</th>
		  <th>Cumulative Difficulty</th>
		  <th># kernel</th>
		  <th># in</th>
		  <th># out</th>
		</tr>
	  </thead>
	  <tbody>
		{% for blk in results %}
		  <tr>
			<td><a href="/block/{{ blk.hash }}">{{ blk.hash }}</a></td>
			<td>{{ blk.timestamp | naturaltime}}</td>
			<td>{{ blk.total_difficulty | intcomma }}</td>
			<td>{{ blk.kernel_set.all.count }}</td>
			<td>{{ blk.input_set.all.count }}</td>
			<td>{{ blk.output_set.all.count }}</td>
		  </tr>
		{% endfor %}
	  </tbody>
	</table>
  {% else %}
	{% if q_isdigit %}
	  <p>
		We couldn't find a block at height <strong>{{ q }}</strong>.
	  </p>
	{% elif q|length < 6 %}
	  <p>
		Your search term <strong>{{ q }}</strong> is too short, please enter at least six characters if searching by hash.
	  </p>
	{% else %}
	  <p>
		We couldn't find any blocks starting with the hash <strong>{{ q }}</strong>.
	  </p>
	{% endif %}
  {% endif %}
{% endblock content %}

app/css/grinexplorer/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
	<title>GrinExplorer</title>
	<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
	<link rel="stylesheet" href="{% static "css/project.css" %}">
	<link rel="stylesheet" href="{% static "css/fontawesome-all.min.css" %}">
  </head>
  <body>
	<div class="container">
	  <div class="row align-items-start">
		<div class="col">
		  <h1><a href="/">GrinExplorer</a></h1>
		</div>
		<div class="col text-right">
		  <form method="get" action="/search" style="margin-top:12px;">
			<div class="input-group">
			  <input class="form-control" type="search" name="q" placeholder="Search by block hash or height" size="66">
			  <div class="input-group-btn">
				<button type="submit" class="btn btn-secondary"><i class="fas fa-search"></i></button>
			  </div>
			</div>
		  </form>
		</div>
	  </div>

	  {% block content %}{% endblock content %}
	</div>

	<footer>
	  <a href="https://grinexplorer.net/">GrinExplorer.net</a> is powered by <a href="https://github.com/mimblewimble/grin-explorer">grin-explorer</a> released under the GNU AGPL.
	</footer>
  </body>
</html>